import React from 'react';
import { Recommendation } from '../../types';
import { ShieldAlert, AlertCircle, CheckSquare, Info } from 'lucide-react';

interface RecommendationsCardProps {
  recommendations: Recommendation[];
}

export const RecommendationsCard: React.FC<RecommendationsCardProps> = ({ recommendations }) => {
  return (
    <div className="bg-[#111827] border border-[#1f293d] rounded-xl p-6 space-y-4">
      <div className="flex items-center justify-between border-b border-[#1f293d] pb-3">
        <div className="flex items-center space-x-2">
          <ShieldAlert className="w-5 h-5 text-blue-400" />
          <h2 className="text-base font-bold text-slate-100 tracking-wide">Recommended Investigation & Containment Actions</h2>
        </div>
        <span className="px-2.5 py-1 text-[10px] font-mono bg-blue-500/10 text-blue-400 border border-blue-500/30 rounded-md font-semibold uppercase">
          Analyst Guidance Only
        </span>
      </div>

      {/* Disclaimer Banner */}
      <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-lg text-amber-300 text-xs font-mono flex items-start gap-2.5">
        <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <strong>Automated Policy Guidance Disclaimer:</strong> Recommendations are suggested workflow actions generated by SentinelIQ. No response action is executed autonomously.
        </div>
      </div>

      <div className="space-y-3">
        {recommendations.map((rec, idx) => {
          const isImmediate = rec.priority === 'IMMEDIATE';
          return (
            <div key={idx} className="p-4 bg-[#0f172a] border border-[#1f293d] rounded-xl space-y-2">
              <div className="flex items-center justify-between font-mono text-xs">
                <div className="flex items-center space-x-2">
                  <span className={`px-2 py-0.5 text-[10px] font-bold rounded border ${
                    isImmediate ? 'bg-rose-500/20 text-rose-300 border-rose-500/40' :
                    rec.priority === 'HIGH' ? 'bg-amber-500/20 text-amber-300 border-amber-500/30' :
                    'bg-blue-500/15 text-blue-300 border-blue-500/30'
                  }`}>
                    [{rec.priority}]
                  </span>
                  <h3 className="font-bold text-slate-100 text-sm">{rec.action}</h3>
                </div>
                <span className="px-2 py-0.5 bg-slate-800 text-slate-400 rounded text-[10px] font-semibold">
                  STATUS: {rec.status}
                </span>
              </div>

              <p className="text-xs text-slate-300 font-mono leading-relaxed pl-1">{rec.details}</p>

              <div className="pt-2 border-t border-[#1f293d]/50 flex items-center justify-between text-[11px] font-mono text-slate-400">
                <span className="flex items-center gap-1 text-blue-400">
                  <CheckSquare className="w-3.5 h-3.5" />
                  Automated Recommendation
                </span>
                <span className="italic text-[10px]">Action required by SOC Analyst</span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
